---
title: "TDR Analysis"
author: "Kevin L. Stierhoff"
date: "`r Sys.Date()`"
output: html_document
---

```{r set-up,echo=F,message=F,warning=F,error=F,include=F}
# Install and load pacman (library management package)
if (!require("pacman")) install.packages("pacman")
if (!require("pak")) install.packages("pak")

# Install and load required packages from CRAN ---------------------------------
pacman::p_load(tidyverse,plotly,lubridate,here,DBI,odbc,
               knitr,DT,fs,oce,sf,mapview,shadowtext,
               patchwork,RSQLite,xts,progress,plotly)

# Install and load required packages from Github -------------------------------
if (!require("atm")) pkg_install("SWFSC/atm")
pacman::p_load_gh("SWFSC/atm")

if (!require("surveyR")) pkg_install("SWFSC/surveyR")
pacman::p_load_gh("SWFSC/surveyR")

# Knitr options
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE,
                      out.width = "90%")

theme_set(theme_bw())
```

```{r user-settings}
# User-specified settings
copy.files   <- F # Copy TDR files
process.rsk  <- T # Process RBR Duet^3^ TDR files (.rsk format)
process.asc  <- T # Process Seabird TDR files (.asc format)
process.tv80 <- T # Process Simrad TV80 data

# Usually F; set T to reprocess all TDR/TV80 files
process.tdr.all   <- F # Process all TDR files 
process.tv80.all  <- T # Process all TV80 files

get.db      <- F # Extract data from trawl database (F for testing)
get.nav     <- T # Download NOAA Ship nav data
save.figs   <- F # Save figures
```

# Process trawl haul data

```{r collect-trawl-data}
if (get.db) {
  # Create directory for trawl data
  dir_create(here("Data/Trawl"))
  
  # Source script to collect data from trawl database
  # source(here("Code/collect_trawl_database.R"))
  
  # Configure ODBC connection to TRAWL database
  trawl.con <- DBI::dbConnect(odbc::odbc(),
                              DRIVER="ODBC Driver 18 for SQL Server",
                              Encrypt = "Optional",
                              DATABASE="Trawl",
                              Trusted_Connection= "Yes",
                              SERVER="swc-estrella-s")
  
  # Get haul info
  haul <- dplyr::tbl(trawl.con,"Haul")  %>% dplyr::collect()
  
  # Close database channel
  DBI::dbDisconnect(trawl.con)
  
  # Save database data
  save(haul, file = here::here("Data/Trawl/trawl_data_raw.Rdata"))
  
} else {
  # Load trawl data
  load(here("Data/Trawl/trawl_data_raw.Rdata"))
  
}
```

```{r format-trawl-data}
# Source script to format data from trawl database
# source(here("Code/format_trawl_database.R"))

# Format haul info
haul <- haul %>% 
  arrange(cruise, ship, haul) %>% 
  mutate(
    netInWaterTime  = ymd_hms(netInWaterTime),
    equilibriumTime = ymd_hms(equilibriumTime),
    haulBackTime    = ymd_hms(haulBackTime),
    netOnDeckTime   = ymd_hms(netOnDeckTime)) %>% 
  mutate(deploymentTime = difftime(equilibriumTime, netInWaterTime, units = "mins"),
         recoveryTime   = difftime(netOnDeckTime, haulBackTime, units = "mins"),
         evolutionTime  = difftime(netOnDeckTime, netInWaterTime, units = "mins")) %>% 
  mutate(season = case_when(
    month(equilibriumTime) < 6 ~ "spring",
    TRUE ~ "summer"))

# Calculate mean latitude, for converting pressure to depth
mean.lat = mean(haul$startLatDecimal, na.rm = T)
```

# Copy TDR data from each survey

Done manually for now. Code below not run.

```{r copy-files, eval=FALSE}
if (copy.files) {
  # Create directory for TDR files -------------------------------------------------  
  dir_create(here("Data/TDR", , c("Kite","Footrope")))
  
  # Copy TDR files
  tdr.files.kite <- dir_ls(file.path(survey.dir[survey.vessel.primary], "DATA/TDR/Kite"),
                           regexp = tdr.pattern)
  file_copy(tdr.files.kite, here("Data/TDR/Kite"), overwrite = TRUE)
  
  tdr.files.foot <- dir_ls(file.path(survey.dir[survey.vessel.primary], "DATA/TDR/Footrope"),
                           regexp = tdr.pattern)
  file_copy(tdr.files.foot, here("Data/TDR/Footrope"), overwrite = TRUE)
  
  # Create directory for TV80 files -------------------------------------------------
  dir_create(here("Data/TV80"))
  
  # Copy TV80 files
  tv80.files <- dir_ls(file.path(survey.dir[survey.vessel.primary], "DATA/TV80"),
                       regexp = "*measurements.csv", recurse = TRUE)
  
  # Copy files where file is empty (size > 0 bytes)
  file_copy(tv80.files[file_info(tv80.files)$size>0], here("Data/TV80"), overwrite = TRUE)
}
```

# Process TDR files

```{r process-tdr-files}
if (process.tdr.all) {
  # Create tbl for all TDR data
  tbl.tdr.all <- data.frame()
  
  # Read TDR info file for fixing date/time/etc.
  tdr.info <- read_csv(here("Data/TDR/tdr-info.csv")) %>% 
    mutate(cruise = as.character(cruise))
  
  # For each directory in Data/TDR (grouped by survey)
  for (i in dir_ls(here("Data/TDR"), type = "directory")) {
    # i = dir_ls(here("Data/TDR"), type = "directory")[1]
    tbl.tdr.cruise <- data.frame()
    
    # For each location (Kite/Footrope)
    for (ii in dir_ls(i, type = "directory")) {
      # ii = dir_ls(i, type = "directory", regexp = "Footrope")
      # ii = dir_ls(i, type = "directory", regexp = "Kite") 
      
      # Print update message
      cat("Processing", ii, "\n")
      
      # Create progress bar
      pb <- progress_bar$new(total = length(dir_ls(ii)), 
                             format = "[:bar] :percent :eta",
                             width = 50)
      
      for (iii in dir_ls(ii)){
        # iii = dir_ls(ii)[1]
        
        # # Rename files
        # files_to_rename <- dir_ls(ii) # Lists all TDR files
        # new_names <- stringr::str_replace(files_to_rename, "2307RL", "202307RL")
        # 
        # # Renaming multiple files
        # file_move(path = files_to_rename, new_path = new_names)
        
        if (str_detect(tolower(path_ext(iii)),"rsk")) {
          # Extract TDR data from RSK file
          # Read kite TDR file
          rsk.tmp <- read.rsk(iii)
          
          # Create temporary variables
          tdr.filename <- path_file(rsk.tmp@metadata$filename)
          tdr.cruise   <- str_sub(tdr.filename, 1,6)
          tdr.haul     <- as.numeric(str_sub(tdr.filename, 
                                             nchar(tdr.cruise) + 3, 
                                             nchar(tdr.cruise) + 5))
          
          tbl.tmp <- as_tibble(rsk.tmp@data) %>% 
            mutate(filename = tdr.filename,
                   cruise   = tdr.cruise, 
                   haul     = tdr.haul,
                   depth    = surveyR::calc_depth(mean.lat, pressure*100),
                   loc      = ifelse(str_detect(iii, "FR.rsk"), "Footrope", "Kite"))
          
          # Update progress bar
          pb$tick()
          
        } else if (str_detect(tolower(path_ext(iii)),"asc")) {
          # Extract TDR data from ASCII file
        }
        
        # Combine with data from rest of cruise
        tbl.tdr.cruise <- bind_rows(tbl.tdr.cruise, tbl.tmp)
      }
    }
    
    # Save results
    save(tbl.tdr.cruise, file = here(i, paste0(basename(i), "_tdr_raw.Rdata")))
    
    # Combine data from cruise with all data
    tbl.tdr.all <- bind_rows(tbl.tdr.all, tbl.tdr.cruise)
  }
  
  # Save processing results
  save(tbl.tdr.all, file = here("Data/TDR/all_tdr_raw.Rdata"))
  
  # Apply time fix, depth offset, and gear type to TDR data
  tbl.tdr.all <- tbl.tdr.all %>% 
    left_join(tdr.info) %>% 
    mutate(time = force_tz(time, tz = tz),
           time.utc = with_tz(time, tzone = "UTC") +
             years(offset.y) + months(offset.m) + days(offset.d) +
             hours(offset.H) + minutes(offset.M)) %>% 
    mutate(depth = depth + offset.z)  %>% 
    mutate(key = paste(cruise, haul)) %>% 
    left_join(select(haul, cruise, haul, gearType)) %>% 
    arrange(loc, time.utc)
  
  # Save corrected results
  save(tbl.tdr.all, file = here("Data/TDR/all_tdr.Rdata"))
  
} else {
  load(here("Data/TDR/all_tdr.Rdata"))
}

if (process.tdr.all) {
  # Extract data during fishing
  # Create df for storing TDR data
  tdr.fishing <- data.frame()
  
  # Extract fishing data
  for (i in unique(tbl.tdr.all$key)) {
    # Get haul info
    haul.tmp <- haul %>%
      mutate(key = paste(cruise, haul)) %>% 
      filter(key == i)
    
    # Subset TDR data and extract fishing data
    tdr.tmp <- tbl.tdr.all %>%
      filter(key == i) %>% 
      filter(between(time.utc, haul.tmp$equilibriumTime, haul.tmp$haulBackTime)) %>% 
      select(cruise, haul, time.utc, loc, depth)
    
    if ("Kite" %in% tdr.tmp$loc & "Footrope" %in% tdr.tmp$loc) {
      # For hauls that have both kite and footrope TDRs
      # Calculate relative time from start of fishing
      tdr.tmp <- tdr.tmp %>% 
        pivot_wider(names_from = loc, values_from = depth) %>% 
        mutate(time.diff = c(0, diff(time.utc)),
               time.cum  = cumsum(time.diff)/60,
               height = Kite - Footrope) %>% 
        mutate(key = i)
      
      # Combine results
      tdr.fishing <- bind_rows(tdr.tmp, tdr.fishing)
    }
  }
  
  # Save processed data
  save(tdr.fishing, file = here("Data/TDR/tdr_data_fishing.Rdata"))
} else {
  # Load processed data
  load(here("Data/TDR/tdr_data_fishing.Rdata"))
}
```

```{r debug-tdr-times,eval=FALSE}
# # Define gear type
# tdr.fishing <- tdr.fishing %>% 
#   mutate(gear.type = case_when(
#     cruise %in% c("202407, 202506") ~ "MFT",
#     TRUE ~ "Nordic"
#   ))

# # # Subset tdr.fishing per cruise
# tdr.fishing.sub <- filter(tdr.fishing, cruise == "202107")
#  
# tmp.plot <- ggplot(tdr.fishing.sub) +
#   geom_path(aes(time.cum, height, group = haul), colour = "green") +
#   labs(x = "Cumulative time (mins)", y = "Opening height (m)")
# 
# plotly::ggplotly(tmp.plot)
# 
# ggplot(filter(tdr.fishing.sub, haul == 28)) +
#   geom_path(aes(time.cum, Kite, group = haul), colour = "red") +
#   geom_path(aes(time.cum, Footrope, group = haul), colour = "blue") +
#   labs(x = "Cumulative time (mins)", y = "Depth (m)",
#        title = paste("Cruise: ", unique(tdr.fishing.sub$cruise),
#                      "Gear type: ", unique(tdr.fishing.sub$gear.type)))

```

```{r plot-fishing-data}
if (save.figs) {
  # Save TDR depth plots
  tdr.plot.depths <- ggplot(filter(tdr.fishing, time.cum < 45)) +
    geom_path(aes(time.cum, Kite, group = haul), colour = "red", alpha = 0.3) +
    geom_path(aes(time.cum, Footrope, group = haul), colour = "blue", alpha = 0.3) +
    facet_wrap(~cruise, nrow = 2)
  
  ggsave(tdr.plot.depths, 
         filename = here("Figs/fig_tdr_depths_all_facet.png"),
         width = 10, height = 10)
  
  tdr.plot.heights <- ggplot(filter(tdr.fishing, time.cum < 45)) +
    # ggplot(filter(tdr.fishing, time.cum < 45, height > 0)) +
    geom_path(aes(time.cum, height, group = haul), colour = "green") +
    facet_wrap(~cruise, nrow = 2)
  
  ggsave(tdr.plot.heights, 
         filename = here("Figs/fig_tdr_heights_all_facet.png"),
         width = 10, height = 10)
}
```

# Process navigation data

Hold off on this for now.

```{r get-nav, eval=FALSE}
if (get.nav) {
  nav.all <- data.frame()
  
  for (j in dir_ls(here("Data/Nav"), regexp = "*.Rdata")) {
    # j = dir_ls(here("Data/Nav"), regexp = "*.Rdata")[1]
    
    # Load nav data file
    load(j)
    
    # Add cruise name to nav data
    nav <- nav %>% 
      mutate(cruise = str_extract(j, pattern = "\\d{6}"))
    
    # Combine all cruises
    nav.all <- bind_rows(nav.all, nav)
  }
  
  # Save all nav data
  saveRDS(nav.all, here("Data/Nav/nav-all.rds"))
} else {
  # Load processed nav data
  nav <- readRDS(here("Data/Nav/nav-all.rds"))
  # ggplot(nav.all, aes(long, lat, colour = cruise)) + geom_path() + coord_map() + facet_wrap(~cruise)
}

# Create df for all results
tdr.nav.all <- data.frame()

for (k in unique(tdr.fishing$cruise)) {
  # k = "202107"
  
  tdr.nav.cruise <- data.frame()
  
  tdr.sub <- filter(tdr.fishing, cruise == k)
  
  for (kk in unique(tdr.sub$haul)) {
    # kk=4
    # Extract TDR data for each haul
    tdr.tmp <- filter(tdr.sub, haul == kk)
    
    # Extract nav data during the fishing period
    nav.tmp <- filter(nav, between(time, min(tdr.tmp$time.utc), max(tdr.tmp$time.utc))) %>% 
      mutate(period = "Fishing",
             cruise = unique(tdr.tmp$cruise),
             haul = kk)    
    
    tdr.nav.cruise <- bind_rows(tdr.nav.cruise, nav.tmp)
  }
  
  tdr.nav.all <- bind_rows(tdr.nav.all, tdr.nav.cruise)
}

tdr.nav.sf <- tdr.nav.all %>% 
  st_as_sf(coords = c("long","lat"), crs = 4326) 

tdr.paths.sf <- tdr.nav.sf %>% 
  group_by(cruise, haul, period) %>% 
  summarise(do_union = FALSE) %>% 
  st_cast("LINESTRING")

nav.paths <- nav %>% 
  st_as_sf(coords = c("long","lat"), crs = 4326) %>% 
  group_by(cruise) %>% 
  summarise(do_union = FALSE) %>% 
  st_cast("LINESTRING")

# Perimeter of an ellipse with a 18m high opening and a 36m wide opening is 87.2m
# Mouth opening of the Nordic264 was nominally 336m2 (12 meters by 28m)
# LITZ ET AL.: NORTHERN ANCHOVY ECOLOGY AND DISTRIBUTION CalCOFI Rep., Vol. 49, 2008
# Mouth opening of the MFT was nominally 648m2 (18 meters by 36m)
# Pers. comm.: S. Melly

# tdr.fishing <- tdr.fishing %>% 
#   mutate(time.align = align.time(time.utc, n = 60)) %>% 
#   left_join(select(nav, time.align = time, SOG, lat, long, cruise.nav = cruise)) %>% 
#   # Compute distance
#   mutate() %>% 
#   # Compute area
#   mutate() 
#   # Compute volume

# cruise.name = "202506"
# 
# mapview::mapview(filter(nav.paths, cruise == cruise.name),color = "gray40") + 
#   mapview::mapview(filter(tdr.paths.sf, cruise == cruise.name), color = "green")

# ggplot(tdr.nav.haul, aes(long, lat, group = haul)) + geom_path()


# Plot trawl paths
```

```{r plot-tdr-results, eval=FALSE}
# # Plot results
# tdr.info <- read_csv(here("Data/TDR/tdr-info.csv")) %>% 
#   mutate(cruise = as.character(cruise))

tdr.plot <- tdr.fishing %>% 
  filter(cruise == "202107")

# Get time info for comparison with trawl database
tdr.summary <- tdr.plot %>%
  # filter(haul %in% c(28)) %>%
  group_by(cruise, haul, loc) %>%
  summarise(min.time = min(time.utc),
            max.time = max(time.utc)) %>%
  left_join(select(haul, cruise, haul, netInWaterTime, equilibriumTime)) %>%
  mutate(time.diff = -difftime(min.time, netInWaterTime, units = "hours"))

haul.min <- 121
haul.max <- haul.min + 29

tdr.plot.sub <- filter(tdr.plot, between(haul, haul.min, haul.max))

# filter(tdr.plot, haul == 25) %>% group_by(loc) %>% summarise(min.time = min(time.utc))

# tdr.plot %>% group_by(haul, loc) %>% summarise(min.time = min(time.utc)) %>% 
#   pivot_wider(names_from = loc, values_from = min.time) %>% 
#   mutate(diff.time = difftime(Footrope, Kite, units = "mins")) %>% View()

trawl.window <- haul %>% 
  filter(between(haul, haul.min, haul.max),
         cruise %in% unique(tdr.plot$cruise))

# Plot results
ggplot() + 
  geom_hline(yintercept = 0) +
  geom_path(data = tdr.plot.sub, 
            aes(time.utc, depth, group = loc, colour = loc)) +
  geom_rect(data = trawl.window,
            aes(xmin = equilibriumTime,
                xmax = haulBackTime,
                ymin = -60,
                ymax = 5),
            fill = 'gray70', alpha = 0.5) +
  geom_rect(data = trawl.window,
            aes(xmin = netInWaterTime,
                xmax = netOnDeckTime,
                ymin = -60,
                ymax = 5), fill = NA,
            colour = 'gray50', linetype = "dashed", alpha = 0.5) +
  facet_wrap(~haul, scales = "free", nrow = 5, ncol = 6) 
```




